language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1.6
  - 2.2.2
  - rbx-2
  - ruby-head

before_script:
  - RAILS_ENV=test bundle exec rake db:schema:load

script:
  - bundle exec rake test

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
